---
name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: |
          git config --global user.name "github"
          git config --global user.name "github"
          make test
      - run: make all
