---
name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "github"
          git config --global user.name "github"
          make test
      - run: make all
  automerge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: automerge
        uses: mhristof/github-action-automerge@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
